/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IAidServiceProvider } from "../IAidServiceProvider";

export class IAidServiceProvider__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAidServiceProvider {
    return new Contract(address, _abi, signerOrProvider) as IAidServiceProvider;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_firstIdentity",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
