/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IAidIssuer } from "../IAidIssuer";

export class IAidIssuer__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAidIssuer {
    return new Contract(address, _abi, signerOrProvider) as IAidIssuer;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_firstIdentity",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_identityIssuer",
        type: "address",
      },
    ],
    name: "isIdentityIssuer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
