/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface AlastriaIdentityServiceProviderInterface
  extends ethers.utils.Interface {
  functions: {
    "addIdentityServiceProvider(address)": FunctionFragment;
    "deleteIdentityServiceProvider(address)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "isIdentityServiceProvider(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addIdentityServiceProvider",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteIdentityServiceProvider",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isIdentityServiceProvider",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addIdentityServiceProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteIdentityServiceProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isIdentityServiceProvider",
    data: BytesLike
  ): Result;

  events: {};
}

export class AlastriaIdentityServiceProvider extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: AlastriaIdentityServiceProviderInterface;

  functions: {
    addIdentityServiceProvider(
      _identityServiceProvider: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addIdentityServiceProvider(address)"(
      _identityServiceProvider: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    deleteIdentityServiceProvider(
      _identityServiceProvider: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deleteIdentityServiceProvider(address)"(
      _identityServiceProvider: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initialize(
      _firstIdentity: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address)"(
      _firstIdentity: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isIdentityServiceProvider(
      _identityServiceProvider: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isIdentityServiceProvider(address)"(
      _identityServiceProvider: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  addIdentityServiceProvider(
    _identityServiceProvider: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addIdentityServiceProvider(address)"(
    _identityServiceProvider: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  deleteIdentityServiceProvider(
    _identityServiceProvider: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "deleteIdentityServiceProvider(address)"(
    _identityServiceProvider: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initialize(
    _firstIdentity: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address)"(
    _firstIdentity: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isIdentityServiceProvider(
    _identityServiceProvider: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isIdentityServiceProvider(address)"(
    _identityServiceProvider: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    addIdentityServiceProvider(
      _identityServiceProvider: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "addIdentityServiceProvider(address)"(
      _identityServiceProvider: string,
      overrides?: CallOverrides
    ): Promise<void>;

    deleteIdentityServiceProvider(
      _identityServiceProvider: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "deleteIdentityServiceProvider(address)"(
      _identityServiceProvider: string,
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(
      _firstIdentity: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address)"(
      _firstIdentity: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isIdentityServiceProvider(
      _identityServiceProvider: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isIdentityServiceProvider(address)"(
      _identityServiceProvider: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    addIdentityServiceProvider(
      _identityServiceProvider: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addIdentityServiceProvider(address)"(
      _identityServiceProvider: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    deleteIdentityServiceProvider(
      _identityServiceProvider: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "deleteIdentityServiceProvider(address)"(
      _identityServiceProvider: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    initialize(
      _firstIdentity: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address)"(
      _firstIdentity: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isIdentityServiceProvider(
      _identityServiceProvider: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isIdentityServiceProvider(address)"(
      _identityServiceProvider: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addIdentityServiceProvider(
      _identityServiceProvider: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addIdentityServiceProvider(address)"(
      _identityServiceProvider: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    deleteIdentityServiceProvider(
      _identityServiceProvider: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deleteIdentityServiceProvider(address)"(
      _identityServiceProvider: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _firstIdentity: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address)"(
      _firstIdentity: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isIdentityServiceProvider(
      _identityServiceProvider: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isIdentityServiceProvider(address)"(
      _identityServiceProvider: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
