/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IAidIssuerInterface extends ethers.utils.Interface {
  functions: {
    "initialize(address)": FunctionFragment;
    "isIdentityIssuer(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isIdentityIssuer",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isIdentityIssuer",
    data: BytesLike
  ): Result;

  events: {};
}

export class IAidIssuer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IAidIssuerInterface;

  functions: {
    initialize(
      _firstIdentity: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address)"(
      _firstIdentity: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isIdentityIssuer(
      _identityIssuer: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isIdentityIssuer(address)"(
      _identityIssuer: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  initialize(
    _firstIdentity: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address)"(
    _firstIdentity: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isIdentityIssuer(
    _identityIssuer: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isIdentityIssuer(address)"(
    _identityIssuer: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    initialize(
      _firstIdentity: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address)"(
      _firstIdentity: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isIdentityIssuer(
      _identityIssuer: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isIdentityIssuer(address)"(
      _identityIssuer: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    initialize(
      _firstIdentity: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address)"(
      _firstIdentity: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isIdentityIssuer(
      _identityIssuer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isIdentityIssuer(address)"(
      _identityIssuer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    initialize(
      _firstIdentity: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address)"(
      _firstIdentity: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isIdentityIssuer(
      _identityIssuer: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isIdentityIssuer(address)"(
      _identityIssuer: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
